version: '3.8'

volumes:
  postgres_volume:

services:
  db:
    container_name: sync-alg-container
    image: postgres:14-alpine3.15
    environment:
      - "POSTGRES_DB=sync-alg-db"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=qwerty"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data